### ISSUE TITLE
Error: Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by zalow517** [matteofigus/api-benchmark#11]
I don't see any references to restricting http-only calls in your library, however when I am trying to reach a service which is https-based I am getting a null returned.

Any suggestions please? Thanks!

**Comment by matteofigus** [comment]
Https is supported and I use this tool myself to benchmark across https services. 
Can you share your code? And what is null? The value of the results callback?

Thanks
Matteo

**Comment by zalow517** [comment]
Ah my bad... didn't realize it was returning an error:
self signed certificate in certificate chain

**Comment by matteofigus** [comment]
Uhm, I got a similar problem recently with a specific node.js version. Can you try upgrading node to >= 0.10.35 and see if the issue persists? In my case, I solved it this way

**Comment by zalow517** [comment]
Hmm I'm running on v0.12.0. I'll try setting up the web-server on my own machine instead of local-network and see how it goes from there.

**Comment by matteofigus** [comment]
I made a quick research. Given we use superagent to do the actual requests, I found some issues and PRs related to self-signed certificates: https://github.com/visionmedia/superagent/pull/198

So, now I need to understand how to solve it here.

**Comment by zalow517** [comment]
Ok cool! I don't know if it will help, but for now I solved the issue by adding: process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

**Comment by matteofigus** [comment]
Looks like node by default used to accept self-signed certificates and this changed very recently. This setting fixes it. Closing the issue so. Thanks for your contribute

Matteo
