### ISSUE TITLE
Receiving "Maximum call stack size exceeded" even if the options are configured as low as 2.

### ISSUE THREAD

**Issue by rcramu** [matteofigus/api-benchmark#12]
Hi ,
I am receiving below error:
--------------------------------------------------------------------
\node_modules\api-benchmark\lib\runner.js:177
      var results = {};
      ^
RangeError: Maximum call stack size exceeded
--------------------------------------------------------------------
Options are as below:

----------------------------

var options = {
    "minSamples": 10,
    "runMode": "parallel",
    "maxConcurrentRequests": 2,
    "debug": true,
    "stopOnError": false
  };

Thanks in advance.

**Comment by matteofigus** [comment]
Hi, can I know:
* Nodejs version
* api-benchmark version
* OS details

Thanks,
Matteo

**Comment by rcramu** [comment]
Hi ,

Nodejs version : 0.12.2
api-benchmark version: Recent Version
OS details: Windows 7

Thanks,
Ramu

**Comment by matteofigus** [comment]
Please, can you try to [increase your stack size](http://stackoverflow.com/questions/11332422/how-can-i-increase-the-maximum-call-stack-size-in-node-js) and tell me if the error persists?

**Comment by matteofigus** [comment]
Never got an answer for that, so I'm closing. We can always reopen.
