### ISSUE TITLE
Ability to set api service and endpoint titles

### ISSUE THREAD

**Issue by dmyers** [matteofigus/api-benchmark#13]
Rather than use the object key would it be possible to just set a property with the names?

**Comment by matteofigus** [comment]
Hi, can I know the reason? You can still have fancy names as keys if you need?

```js 
{ hello: 'world' }
// or
{ 'this is a name with Fancy spaces etc...': 1234 }
```

**Comment by dmyers** [comment]
Yeah I was having trouble concatenating some variable as keys. So mine ended up being like this:

```javascript
var endpoints = {};
endpoints['Show Place '+placeName] = {
   'route': 'place/'+placeId
}
```
