### ISSUE TITLE
Ability to chain sync calls

### ISSUE THREAD

**Issue by dmyers** [matteofigus/api-benchmark#14]
Do you think it would be nice to be able to chain endpoints somehow? Some REST APIs need to be chained from a previous request body like identifiers in order to query the next and could be done somewhat synchronous.

**Comment by matteofigus** [comment]
It definitely would be nice, the challenge is to make everything performant, perhaps having a supervisor that spins-up a thread of each chain level and coordinates the job between them. This is not easy, but I really would like to do it.
