### ISSUE TITLE
Build HTML server side

### ISSUE THREAD

**Issue by dmyers** [matteofigus/api-benchmark#22]
@matteofigus What do you think about build the HTML server side? My results JSON is 835kb sent to the browser and takes quite a while for it to build the elements client side. I wonder if something like Handlebars could be used too.

**Comment by matteofigus** [comment]
Yes, we can make this a little bit better, but I still would like to keep it minimal (so avoid handlebars) to keep dependencies as less as possible. @tpgmartin maybe you would be interested on helping with this? :+1:

**Comment by tpgmartin** [comment]
Sure sign me up :+1:

**Comment by dmyers** [comment]
@matteofigus Yeah that is a good point on keeping a light footprint.

@tpgmartin Think you will still be able to work on it?

**Comment by tpgmartin** [comment]
@dmyers Sure I'm available
