### ISSUE TITLE
Track benchmark completed time

### ISSUE THREAD

**Issue by dmyers** [matteofigus/api-benchmark#23]
Is there a way to track how long it took run the benchmark? I was thinking under the generated date in the report view there could also be like a time it took to complete the benchmark which could be returned in the results object.

**Comment by matteofigus** [comment]
Well there is a partial time for each series (each endpoint). You mean having a global timer?

**Comment by dmyers** [comment]
Yeah I think that would be pretty nice to have if you think so too. I could track it when I run the benchmark in my project, but I think it would be neat to put in the report view in this one.
