### ISSUE TITLE
Expected response body handler callback

### ISSUE THREAD

**Issue by dmyers** [matteofigus/api-benchmark#27]
@matteofigus In order to find API routes that have errors, in addition to status code checking, I was thinking it could be useful to be able to pass a callback handler which is passed the response object and can determine if the response body is what is expected and would return a boolean.

**Comment by matteofigus** [comment]
We could emit an event for each request with the response body, problem is that parsing would block the single-threaded event-loop and affect results. We should split this in order to use a separate thread so it is actually a little bit complicated.

**Comment by dmyers** [comment]
Ah good call. Might be best to keep it out then I hadn't thought of that.
