### ISSUE TITLE
Dynamic request data

### ISSUE THREAD

**Issue by tiagoboldt** [matteofigus/api-benchmark#51]
I've got an use case where I would like to submit different data per request and evaluate the overall performance of the API, despite data sent. This would require POST data to be dynamic, possibly changed per request. 

Do you think it would be viable to have the `.measure()` function receiving a function that would generate the data on each request? Or through any other approach?

**Comment by matteofigus** [comment]
Hi, this should be already possible: https://github.com/matteofigus/api-benchmark#data
If you make a post, you can pass `data` as function so that in each req has different data.

```js
var c = 0;
...
data: function(){
  c++;
  return { counter: c };
}
...
```
Same should apply to `query` and `headers` properties

**Comment by tiagoboldt** [comment]
My bad, I haven't thoroughly read the docs. I'll close the issue, leaving just the suggestion of adding an example for it.
