### ISSUE TITLE
timer.js "time count" unit test may be too tight?

### ISSUE THREAD

**Issue by michaelsanford** [matteofigus/api-benchmark#6]
Running `npm test` several times, I saw this failure a few times:
`Uncaught AssertionError: expected 0.009798363 to be within 0.01..0.015`

MacBook Air i7, uptime reports `load averages: 1.94 2.50 2.82` so maybe my system is just bogged down.

**Comment by matteofigus** [comment]
Closing this as I haven't heard about it anymore. Eventually, we can reopen.

**Comment by matteofigus** [comment]
I am reopening this. Need to refactor those tests in order to mock setTimeout and ensure tests are stable.
