### ISSUE TITLE
docker image of api-benchmark

### ISSUE THREAD

**Issue by johnshumon** [matteofigus/api-benchmark#73]
I made docker version of api-benchmark with little bit of extensions. Result of load test of APIs are browsable through an interface. 

Link: [https://hub.docker.com/r/johnshumon/docker-api-benchmar](https://hub.docker.com/r/johnshumon/docker-api-benchmark/)

If you find it a good docker version of the api-benchmark then I would like to integrate docker-version to this repo.

**Comment by matteofigus** [comment]
This is amazing! Would you be able to make a PR to link the docker image into this README? I'm sure it would be useful to a lot of people 👏
