### ISSUE TITLE
Query parameters as a function

### ISSUE THREAD

**Issue by jeltok** [matteofigus/api-benchmark#9]
First of all thank you for creating the benchmark utility, I find it very useful.

My use case is benchmarking a search API endpoint. I am passing an arbitrary number of query parameters (e.g. /search?a1=b1&a2=b2&a3=b3) and performing a GET call.

I can see in docs that api-benchmark allows a function to generate payloads  for each POST call. Would be great if we could have the same ability to dynamically generate/randomize query strings for GET calls.

**Comment by matteofigus** [comment]
Hi, thank you.

The thing you are asking for seems doable. I can try to tackle this asap.

**Comment by jeltok** [comment]
Sounds great! I am sure it will make the great utility even better :-)

**Comment by dmyers** [comment]
I'd really like this too as I need to be able to do it in order to use an API I want to test. Are you still working on this @matteofigus?

**Comment by dmyers** [comment]
This was added with #19. :+1:
